### ISSUE TITLE
Dev Ops Jobs Todo: Project Week 2

### ISSUE THREAD

**Issue by nVarap** [chinmaydr/acedemic-organizer#6]
- [X] Get the Wikipedia API Integration done
- [ ] Get the login API and post done
- [x] Get extra tasks done on the notion
- [X] Help with frontend & backend API integration

Summary: This week, I focused on getting our wikipedia API up and helping our backend developer with the integration of the APIs into the frontend. I worked on AWS and getting our site up and running along with creating multiple API endpoints for what we need to do.

*Next Week*: I'll need to work on getting the login stuff done along with our backend developer
